export const PokemonTypes = {
  Normal: 'primary',
  Fighting: 'secondary',
  Flying: 'dark',
  Poison: 'success',
  Ground: 'warning',
  Rock: 'dark',
  Bug: 'light',
  Ghost: 'dark',
  Steel: 'primary',
  Fire: 'warning',
  Water: 'info',
  Grass: 'success',
  Electric: 'warning',
  Psychic: 'info',
  Ice: 'info',
  Dragon: 'danger',
  Dark: 'dark',
  Fairy: 'light',
}

export const PokemonColor = {
  '0': 'primary',
  '1': 'primary',
  '2': 'secondary',
  '3': 'danger',
  '4': 'success',
  '5': 'warning',
  '6': 'info',
  '7': 'light',
  '8': 'dark',
  '9': 'primary',
  '10': 'secondary',
}