version: "3.7"
services:
  app:
    build: .
    container_name: pokelex
    ports:
      - 5000:80
    depends_on:
      - mongodb-db_container
    environment:
      MONGODB_URI: 'mongodb://root:rootpassword@mongodb-db_container:27017'
  
  mongodb-db_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: